"""
Persuasion-Strategy Annotation Pipeline
========================================

Documents and reproduces, end-to-end, the general process used to produce
multi-label persuasion-strategy annotations on the PersuasionForGood corpus:

    persuader_turns.csv
        --> [1] SLICE into fixed-size batches (e.g. 200-turn batches over a
                target row range)
        --> [2] BUILD 5-turn dialogue context per turn (already embedded in
                the source CSV's `context` column; this step verifies /
                truncates it to the last N turns, matching the protocol)
        --> [3] ASSEMBLE the batch prompt (system prompt from prompt.md +
                the batch's JSON payload) that gets pasted into the LLM
        --> [4] ANNOTATE each batch (in production this is done by
                directly driving an LLM agent turn-by-turn/batch-by-batch
                rather than a scripted API loop -- see AnnotatorClient
                below for the pluggable seam where a real API call would
                go)
        --> [5] VALIDATE each annotated batch against the closed-world
                taxonomy and schema
        --> [6] MERGE all annotated batches into the final long-format
                JSONL/CSV and the wide one-hot CSV
        --> [7] SUMMARIZE (per-label / per-category prevalence stats) into
                SUMMARY.md

This script is a faithful *representation* of the pipeline for review
purposes, parameterized by a target row range rather than hardcoded to any
one annotation run. Step [4] does not call a live model by default -- real
runs used an LLM agent directly, one batch at a time, with a manual
smoke-test checkpoint on the first batch (see prompt.md, Section 5). It
reads already-annotated batch files when present, and only invokes
`AnnotatorClient` for batches that are missing, so that the rest of the
pipeline (slicing, context-building, prompt assembly, validation, merge,
summary) can be run and demonstrated end-to-end without re-annotating.

Usage
-----
    python pipeline.py slice            # [1]+[2] build batch_*.json from persuader_turns.csv
    python pipeline.py build-prompts    # [3] materialize the exact prompt sent per batch
    python pipeline.py annotate         # [4] annotate any batch not already in annotated_batch/
    python pipeline.py validate         # [5] schema/taxonomy check on annotated_batch/*.json
    python pipeline.py merge            # [6]+[7] merge + write SUMMARY.md
    python pipeline.py all              # run every step in order

Range configuration
--------------------
By default the pipeline targets this workspace's run (rows 7001-10600,
batches 36-53, 200 turns/batch). To point it at a different run, override
any of these via CLI flags (apply to every subcommand):

    --first-row N       first 1-indexed row of persuader_turns.csv (default 7001)
    --last-row N        last 1-indexed row, inclusive (default 10600)
    --batch-size N      turns per batch (default 200)
    --first-batch-num N number to assign the first batch (default 36)
    --out-prefix NAME   prefix for merged output files (default claude_multilabel_7001_10600)

Example: python pipeline.py all --first-row 1 --last-row 7000 --first-batch-num 1 --out-prefix claude_multilabel_1_7000
"""

from __future__ import annotations

import argparse
import csv
import json
import re
from collections import Counter, OrderedDict
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths & taxonomy (fixed across runs)
# ---------------------------------------------------------------------------

ROOT = Path(__file__).resolve().parent.parent           # corpus workspace root
WORKSPACE = Path(__file__).resolve().parent              # this run's folder

SOURCE_CSV = ROOT / "persuader_turns.csv"
BATCH_DIR = ROOT / "batch"
ANNOTATED_DIR = ROOT / "annotated_batch"
PROMPTS_DIR = WORKSPACE / "batch_prompts"                # generated by build-prompts
SYSTEM_PROMPT_MD = WORKSPACE / "prompt.md"

CONTEXT_WINDOW_TURNS = 5  # max prior turns kept in `context`
MAX_LABELS = 6

# The closed-world taxonomy (11 categories / 41 strategies) -- must match
# TAXONOMY_CHEATSHEET.md exactly. Used for schema validation in step [5]
# and for building the wide one-hot matrix in step [6]. This does not vary
# by run/row-range.
TAXONOMY: "OrderedDict[str, list[str]]" = OrderedDict([
    ("Rational Appeal", [
        "logical_appeal", "evidence_and_statistics",
        "cost_benefit_framing", "feasibility_and_ease",
    ]),
    ("Emotional Appeal", [
        "emotion_appeal", "guilt_induction",
        "empathy_and_perspective_taking", "hope_and_positive_impact",
    ]),
    ("Credibility Appeal", [
        "organizational_credibility", "transparency_and_accountability",
        "source_citation", "personal_credibility",
    ]),
    ("Social Influence", [
        "social_proof", "self_modeling", "in_group_appeal",
        "authority_endorsement",
    ]),
    ("Reciprocity and Exchange", [
        "reciprocity", "donor_benefit", "gratitude_and_appreciation",
    ]),
    ("Commitment and Consistency", [
        "foot_in_the_door", "door_in_the_face",
        "value_consistency_appeal", "incremental_ask",
    ]),
    ("Framing and Presentation", [
        "anchoring", "minimization_framing",
        "loss_versus_gain_framing", "comparison_framing",
    ]),
    ("Urgency and Scarcity", [
        "urgency_appeal", "scarcity_appeal", "deadline_pressure",
    ]),
    ("Threat and Pressure", [
        "negative_consequence_warning", "persistent_repetition",
        "obligation_pressure",
    ]),
    ("Information Provision", [
        "donation_procedure_information", "organization_information",
        "impact_information", "task_clarification",
    ]),
    ("Relational and Interactive", [
        "personal_story", "personal_related_inquiry",
        "source_related_inquiry", "rapport_building",
    ]),
])

STRATEGY_TO_CATEGORY = {
    strat: cat for cat, strats in TAXONOMY.items() for strat in strats
}
ALL_STRATEGIES = list(STRATEGY_TO_CATEGORY.keys())


# ---------------------------------------------------------------------------
# Run configuration (varies per annotation run)
# ---------------------------------------------------------------------------

class RunConfig:
    """Parameters describing one annotation run over a row range of
    persuader_turns.csv. Everything downstream (batching, prompts,
    output filenames) is derived from this rather than hardcoded.
    """

    def __init__(self, first_row: int, last_row: int, batch_size: int,
                 first_batch_num: int, out_prefix: str):
        self.first_row = first_row
        self.last_row = last_row
        self.batch_size = batch_size
        self.first_batch_num = first_batch_num
        self.out_prefix = out_prefix

    @property
    def batches(self) -> list[tuple[int, int, int]]:
        """List of (batch_num, start_row, end_row), 1-indexed inclusive."""
        n_batches = (self.last_row - self.first_row + 1) // self.batch_size
        return [
            (
                self.first_batch_num + i,
                self.first_row + i * self.batch_size,
                self.first_row + i * self.batch_size + self.batch_size - 1,
            )
            for i in range(n_batches)
        ]

    @property
    def out_jsonl(self) -> Path:
        return WORKSPACE / f"{self.out_prefix}.jsonl"

    @property
    def out_csv(self) -> Path:
        return WORKSPACE / f"{self.out_prefix}.csv"

    @property
    def out_wide_csv(self) -> Path:
        return WORKSPACE / f"{self.out_prefix}_wide.csv"

    @property
    def out_summary(self) -> Path:
        return WORKSPACE / "SUMMARY.md"


def batch_filename(batch_num: int, start: int, end: int) -> str:
    return f"batch_{batch_num}_turns_{start}_{end}.json"


# ---------------------------------------------------------------------------
# [1] + [2] SLICE persuader_turns.csv into fixed-size batches, each turn
#           carrying its <=N-turn dialogue context
# ---------------------------------------------------------------------------

def truncate_context_to_last_n_turns(context: str, n: int = CONTEXT_WINDOW_TURNS) -> str:
    """Keep only the last `n` [Speaker] lines of a context blob.

    The source CSV already stores context pre-truncated to N turns; this
    is a defensive re-application of the same rule so the pipeline does
    not silently depend on upstream formatting.
    """
    if not context:
        return ""
    lines = [ln for ln in context.split("\n") if ln.strip()]
    return "\n".join(lines[-n:])


def load_source_rows() -> list[dict]:
    with open(SOURCE_CSV, encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def slice_into_batches(cfg: RunConfig) -> None:
    """Step [1]+[2]: recreate batch/batch_NN_turns_X_Y.json from the source CSV."""
    rows = load_source_rows()
    if cfg.last_row > len(rows):
        raise ValueError(f"persuader_turns.csv has only {len(rows)} rows, need {cfg.last_row}")

    BATCH_DIR.mkdir(parents=True, exist_ok=True)

    for batch_num, start, end in cfg.batches:
        # 1-indexed, inclusive slice -> 0-indexed python slice
        chunk = rows[start - 1:end]
        batch_turns = []
        for row in chunk:
            batch_turns.append({
                "turn_id": row["turn_id"],
                "conversation_id": row["conversation_id"],
                "dialogue_id": row["dialogue_id"],
                "turn_index": row["turn_index"],
                "persuader_turn_index": row["persuader_turn_index"],
                "n_turns_in_dialogue": row["n_turns_in_dialogue"],
                "text": row["text"],
                "context": truncate_context_to_last_n_turns(row["context"]),
                "binary_label_norm": row.get("binary_label_norm", ""),
                "modifier_norm": row.get("modifier_norm", ""),
            })

        out_path = BATCH_DIR / batch_filename(batch_num, start, end)
        with open(out_path, "w", encoding="utf-8") as f:
            json.dump(batch_turns, f, indent=2, ensure_ascii=False)
        print(f"[slice] batch {batch_num}: rows {start}-{end} -> {out_path.name} "
              f"({len(batch_turns)} turns)")


# ---------------------------------------------------------------------------
# [3] BUILD the exact prompt sent to the LLM for one batch
# ---------------------------------------------------------------------------

def extract_system_prompt() -> str:
    """Pull the fenced ```text``` block under '## 1. System Prompt' from prompt.md."""
    md = SYSTEM_PROMPT_MD.read_text(encoding="utf-8")
    match = re.search(
        r"## 1\. System Prompt.*?```text\n(.*?)\n```",
        md, re.DOTALL,
    )
    if not match:
        raise ValueError("Could not locate system prompt block in prompt.md")
    return match.group(1)


BATCH_USER_TEMPLATE = """\
Please annotate the following batch of {n} Persuader turns from the PersuasionForGood dataset according to the multi-label persuasion strategy guidelines, operational tests, and closed-world taxonomy defined in your system prompt.

For each turn, output a valid JSON object with:
- "turn_id": string
- "dialogue_id": string
- "turn_index": integer
- "strategies": list of strings (exact taxonomy names)
- "categories": list of strings (exact category names)
- "n_labels": integer (number of strategies, 0 to 6)
- "flags": list of strings (e.g. ["empty_set"] if n_labels == 0, else [])
- "note": string (concise Chain-of-Thought explaining your Removal Test and Specific-Beats-General reasoning)
- "text": string (the exact turn text)

Return your response ONLY as a single valid JSON array containing all {n} turn objects.

--- BATCH INPUT DATA ---
{payload}
"""


def build_batch_prompt(batch_num: int, start: int, end: int) -> str:
    batch_path = BATCH_DIR / batch_filename(batch_num, start, end)
    turns = json.loads(batch_path.read_text(encoding="utf-8"))
    payload = json.dumps(turns, indent=2, ensure_ascii=False)
    return BATCH_USER_TEMPLATE.format(n=len(turns), payload=payload)


def build_all_prompts(cfg: RunConfig) -> None:
    """Step [3]: materialize system + user prompt actually pasted per batch."""
    PROMPTS_DIR.mkdir(parents=True, exist_ok=True)
    system_prompt = extract_system_prompt()
    (PROMPTS_DIR / "_system_prompt.txt").write_text(system_prompt, encoding="utf-8")

    for batch_num, start, end in cfg.batches:
        user_prompt = build_batch_prompt(batch_num, start, end)
        out_path = PROMPTS_DIR / f"batch_{batch_num}_prompt.txt"
        out_path.write_text(user_prompt, encoding="utf-8")
        print(f"[build-prompts] batch {batch_num} -> {out_path.name}")


# ---------------------------------------------------------------------------
# [4] ANNOTATE: pluggable seam for the actual labeling step
# ---------------------------------------------------------------------------

class AnnotatorClient:
    """Represents "send system prompt + batch prompt to the LLM, get JSON back".

    In actual runs, annotation is performed by directly driving an LLM
    agent (Claude) turn-by-turn / batch-by-batch inside an interactive
    session -- per prompt.md Section 5's protocol: smoke-test the first
    batch, get human sign-off, then run the remaining batches in sequence.
    There is no scripted API loop.

    This class is the seam where a scripted alternative (e.g. the Claude
    Messages API) would plug in, so the rest of the pipeline is agnostic
    to how a batch actually got annotated. It intentionally raises rather
    than silently fabricating labels.
    """

    def __init__(self, system_prompt: str):
        self.system_prompt = system_prompt

    def annotate_batch(self, user_prompt: str) -> list[dict]:
        raise NotImplementedError(
            "No live model wired up. In production this batch is annotated "
            "by an LLM agent directly (see prompt.md Section 5); to automate "
            "it, call your model provider here with "
            "(system=self.system_prompt, user=user_prompt) and json.loads() "
            "the response."
        )


def annotate_missing_batches(cfg: RunConfig) -> None:
    """Step [4]: annotate any batch whose annotated_batch/*.json is missing."""
    ANNOTATED_DIR.mkdir(parents=True, exist_ok=True)
    system_prompt = extract_system_prompt()
    client = AnnotatorClient(system_prompt)

    for batch_num, start, end in cfg.batches:
        out_path = ANNOTATED_DIR / f"batch_{batch_num}_annotated.json"
        if out_path.exists():
            print(f"[annotate] batch {batch_num}: already annotated, skipping")
            continue

        print(f"[annotate] batch {batch_num}: not yet annotated -- invoking AnnotatorClient")
        user_prompt = build_batch_prompt(batch_num, start, end)
        annotated = client.annotate_batch(user_prompt)
        out_path.write_text(json.dumps(annotated, indent=2, ensure_ascii=False), encoding="utf-8")


# ---------------------------------------------------------------------------
# [5] VALIDATE annotated batches against schema + closed-world taxonomy
# ---------------------------------------------------------------------------

REQUIRED_FIELDS = {
    "turn_id", "dialogue_id", "turn_index", "strategies",
    "categories", "n_labels", "flags", "note", "text",
}


def validate_record(rec: dict) -> list[str]:
    errors = []
    missing = REQUIRED_FIELDS - rec.keys()
    if missing:
        errors.append(f"missing fields {missing}")
        return errors  # can't check further without the fields

    for strat in rec["strategies"]:
        if strat not in STRATEGY_TO_CATEGORY:
            errors.append(f"unknown strategy '{strat}' (not in closed-world taxonomy)")

    expected_categories = {STRATEGY_TO_CATEGORY[s] for s in rec["strategies"] if s in STRATEGY_TO_CATEGORY}
    if set(rec["categories"]) != expected_categories:
        errors.append(
            f"categories {rec['categories']} do not match strategies-derived "
            f"categories {sorted(expected_categories)}"
        )

    if rec["n_labels"] != len(rec["strategies"]):
        errors.append(f"n_labels={rec['n_labels']} != len(strategies)={len(rec['strategies'])}")

    if rec["n_labels"] > MAX_LABELS:
        errors.append(f"n_labels={rec['n_labels']} exceeds schema cap of {MAX_LABELS}")

    if rec["n_labels"] == 0 and "empty_set" not in rec["flags"]:
        errors.append("n_labels == 0 but flags missing 'empty_set'")

    return errors


def resolve_annotated_path(batch_num: int) -> Path:
    """Locate the annotated file for a batch, tolerating known filename
    variants (e.g. an extra underscore) rather than failing the whole run.
    """
    canonical = ANNOTATED_DIR / f"batch_{batch_num}_annotated.json"
    if canonical.exists():
        return canonical
    variant = ANNOTATED_DIR / f"batch_{batch_num}__annotated.json"
    if variant.exists():
        print(f"[merge] NOTE: batch {batch_num} uses non-standard filename "
              f"'{variant.name}' (expected '{canonical.name}')")
        return variant
    raise FileNotFoundError(f"No annotated file found for batch {batch_num} "
                             f"(looked for {canonical.name} and {variant.name})")


def validate_all(cfg: RunConfig) -> bool:
    """Step [5]: validate every annotated_batch/*.json file in this run. Returns True if clean."""
    ok = True
    off_taxonomy = Counter()
    for batch_num, start, end in cfg.batches:
        try:
            path = resolve_annotated_path(batch_num)
        except FileNotFoundError:
            print(f"[validate] batch {batch_num}: MISSING")
            ok = False
            continue

        records = json.loads(path.read_text(encoding="utf-8"))
        expected_n = end - start + 1
        if len(records) != expected_n:
            print(f"[validate] batch {batch_num}: expected {expected_n} turns, found {len(records)}")
            ok = False

        batch_errors = 0
        for rec in records:
            errs = validate_record(rec)
            if errs:
                batch_errors += 1
                for e in errs:
                    print(f"[validate] batch {batch_num} turn {rec.get('turn_id', '?')}: {e}")
            off_taxonomy.update(s for s in rec.get("strategies", []) if s not in STRATEGY_TO_CATEGORY)
        status = "OK" if batch_errors == 0 and len(records) == expected_n else f"{batch_errors} record error(s)"
        print(f"[validate] batch {batch_num}: {status}")
        ok = ok and batch_errors == 0

    if off_taxonomy:
        print(f"\n[validate] off-taxonomy strategy labels found across all batches (known QA issue):")
        for label, n in off_taxonomy.most_common():
            print(f"    '{label}': {n} turn(s)")
        ok = False

    return ok


# ---------------------------------------------------------------------------
# [6] MERGE annotated batches -> long JSONL/CSV + wide one-hot CSV
# ---------------------------------------------------------------------------

def load_all_annotated(cfg: RunConfig) -> list[dict]:
    records = []
    for batch_num, start, end in cfg.batches:
        path = resolve_annotated_path(batch_num)
        records.extend(json.loads(path.read_text(encoding="utf-8")))
    return records


def write_jsonl(records: list[dict], out_path: Path) -> None:
    with open(out_path, "w", encoding="utf-8") as f:
        for rec in records:
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")


def write_long_csv(records: list[dict], out_path: Path) -> None:
    fields = ["turn_id", "dialogue_id", "turn_index", "model", "model_id",
              "strategies", "categories", "n_labels", "flags", "note", "text"]
    with open(out_path, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        for rec in records:
            writer.writerow({
                "turn_id": rec["turn_id"],
                "dialogue_id": rec["dialogue_id"],
                "turn_index": rec["turn_index"],
                "model": "claude",
                "model_id": "claude-opus-5 (manual annotation, not a model run)",
                "strategies": "|".join(rec["strategies"]),
                "categories": "|".join(rec["categories"]),
                "n_labels": rec["n_labels"],
                "flags": "|".join(rec["flags"]),
                "note": rec["note"],
                "text": rec["text"],
            })


def write_wide_csv(records: list[dict], out_path: Path) -> None:
    cat_cols = ["cat_" + c.replace(" ", "_") for c in TAXONOMY.keys()]
    strat_cols = ["has_" + s for s in ALL_STRATEGIES]
    fields = ["turn_id", "dialogue_id"] + strat_cols + cat_cols

    with open(out_path, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        for rec in records:
            row = {"turn_id": rec["turn_id"], "dialogue_id": rec["dialogue_id"]}
            strat_set = set(rec["strategies"])
            cat_set = set(rec["categories"])
            for s in ALL_STRATEGIES:
                row["has_" + s] = int(s in strat_set)
            for c in TAXONOMY.keys():
                row["cat_" + c.replace(" ", "_")] = int(c in cat_set)
            writer.writerow(row)


# ---------------------------------------------------------------------------
# [7] SUMMARIZE -> SUMMARY.md
# ---------------------------------------------------------------------------

def write_summary(records: list[dict], cfg: RunConfig) -> None:
    n_turns = len(records)
    dialogues = {r["dialogue_id"] for r in records}
    per_dialogue = Counter(r["dialogue_id"] for r in records)
    turns_per_dialogue = list(per_dialogue.values())

    n_labels_list = [r["n_labels"] for r in records]
    mean_labels = sum(n_labels_list) / n_turns
    sorted_labels = sorted(n_labels_list)
    median_labels = sorted_labels[n_turns // 2] if n_turns % 2 else \
        (sorted_labels[n_turns // 2 - 1] + sorted_labels[n_turns // 2]) / 2
    variance = sum((x - mean_labels) ** 2 for x in n_labels_list) / n_turns
    std_dev = variance ** 0.5

    empty_set_count = sum(1 for r in records if r["n_labels"] == 0)
    labels_histogram = Counter(n_labels_list)

    cat_counts = Counter()
    strat_counts = Counter()
    for r in records:
        cat_counts.update(set(r["categories"]))
        strat_counts.update(set(r["strategies"]))

    def pct(n: int) -> str:
        return f"{100 * n / n_turns:.1f}"

    batches = cfg.batches
    lines = []
    lines.append("# annotation summary & statistics\n")
    lines.append(
        f"Multi-label persuasion-strategy annotation of rows **{cfg.first_row}-{cfg.last_row}** "
        f"of `persuader_turns.csv` ({len(ALL_STRATEGIES)} strategies / {len(TAXONOMY)} "
        f"categories). Merged from {len(batches)} batches of {cfg.batch_size} turns "
        f"(batches {batches[0][0]}-{batches[-1][0]}).\n"
    )

    lines.append("## Overview\n")
    lines.append("| Metric | Value |")
    lines.append("| --- | --- |")
    lines.append(f"| Turns | {n_turns:,} |")
    lines.append(f"| Dialogues | {len(dialogues)} |")
    lines.append(
        f"| Turns / dialogue | mean {sum(turns_per_dialogue) / len(turns_per_dialogue):.2f} "
        f"(min {min(turns_per_dialogue)}, max {max(turns_per_dialogue)}) |"
    )
    lines.append(f"| Mean labels / turn | {mean_labels:.2f} |")
    lines.append(f"| Median labels / turn | {median_labels} |")
    lines.append(f"| Std. dev. | {std_dev:.2f} |")
    lines.append(f"| Empty-set turns | {empty_set_count} ({pct(empty_set_count)}%) |")
    lines.append(f"| Max labels on a turn | {max(n_labels_list)} |")
    lines.append(f"| Distinct strategies used | {len(strat_counts)} / {len(ALL_STRATEGIES)} |")
    lines.append(f"| Distinct categories used | {len(cat_counts)} / {len(TAXONOMY)} |\n")

    lines.append("## Labels per turn\n")
    lines.append("| Labels | Turns |")
    lines.append("| --- | --- |")
    for k in range(0, max(n_labels_list) + 1):
        lines.append(f"| {k} | {labels_histogram.get(k, 0)} |")
    lines.append("")

    lines.append("## Category prevalence\n")
    lines.append("| Category | Turns | % |")
    lines.append("| --- | --- | --- |")
    for cat, n in cat_counts.most_common():
        lines.append(f"| {cat} | {n} | {pct(n)} |")
    lines.append("")

    lines.append("## Strategy prevalence (all {}) \n".format(len(ALL_STRATEGIES)))
    lines.append("| Strategy | Category | Turns | % |")
    lines.append("| --- | --- | --- | --- |")
    all_sorted = sorted(ALL_STRATEGIES, key=lambda s: strat_counts.get(s, 0), reverse=True)
    for s in all_sorted:
        n = strat_counts.get(s, 0)
        lines.append(f"| {s} | {STRATEGY_TO_CATEGORY[s]} | {n} | {pct(n)} |")

    cfg.out_summary.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[merge] wrote {cfg.out_summary}")


def merge_and_summarize(cfg: RunConfig) -> None:
    """Step [6]+[7]: merge all annotated batches and regenerate outputs."""
    records = load_all_annotated(cfg)
    write_jsonl(records, cfg.out_jsonl)
    write_long_csv(records, cfg.out_csv)
    write_wide_csv(records, cfg.out_wide_csv)
    write_summary(records, cfg)
    print(f"[merge] {len(records)} turns -> {cfg.out_jsonl.name}, {cfg.out_csv.name}, {cfg.out_wide_csv.name}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

STEPS = {
    "slice": slice_into_batches,
    "build-prompts": build_all_prompts,
    "annotate": annotate_missing_batches,
    "validate": validate_all,
    "merge": merge_and_summarize,
}


def parse_args() -> tuple[str, RunConfig]:
    parser = argparse.ArgumentParser(description=__doc__,
                                      formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("step", choices=[*STEPS, "all"])
    parser.add_argument("--first-row", type=int, default=7001,
                         help="first 1-indexed row of persuader_turns.csv (default: 7001)")
    parser.add_argument("--last-row", type=int, default=10600,
                         help="last 1-indexed row, inclusive (default: 10600)")
    parser.add_argument("--batch-size", type=int, default=200,
                         help="turns per batch (default: 200)")
    parser.add_argument("--first-batch-num", type=int, default=36,
                         help="number to assign the first batch (default: 36)")
    parser.add_argument("--out-prefix", default="claude_multilabel_7001_10600",
                         help="prefix for merged output files (default: claude_multilabel_7001_10600)")
    args = parser.parse_args()

    cfg = RunConfig(
        first_row=args.first_row,
        last_row=args.last_row,
        batch_size=args.batch_size,
        first_batch_num=args.first_batch_num,
        out_prefix=args.out_prefix,
    )
    return args.step, cfg


def main() -> None:
    step, cfg = parse_args()
    if step == "all":
        for name, fn in STEPS.items():
            print(f"\n=== [{name}] ===")
            fn(cfg)
    else:
        STEPS[step](cfg)


if __name__ == "__main__":
    main()
